version: '3.7'

services:

  # Backend API
  guardrails-api:
    container_name: guardrails-api
    env_file:
      - ./.env
    build: 
      context: ./api
    command: npm start
    working_dir: /usr/src/guardrails-api
    ports: 
      # - ${PUBLIC_SERVER_PORT}:3000
      - 5000:3000
      - 9229:9229
    volumes:
      - ./api:/usr/src/guardrails-api

  # Dashboard Client
  guardrails-dashboard:
    container_name: guardrails-dashboard
    env_file:
      - ./.env
    build: 
      context: ./dashboard
    command: npm start
    working_dir: /usr/src/guardrails-dashboard
    ports: 
      # - ${PUBLIC_APP_PORT}:3000
      - 3000:3000
    volumes:
      - ./dashboard:/usr/src/guardrails-dashboard

  # Other services
  mongo:
    image: mongo:4
    restart: always
    volumes:
      - mongo:/data/db:rw
    ports:
      - 27017:27017

volumes:
  mongo: